language: ruby

rvm:
  - 2.1.7
  - 2.2.3
  - 2.3.1

sudo: required
dist: trusty

before_install:
  - gem install minitest -v '5.9.0'
  - gem install http -v '2.0.1'
script: ruby test.rb

notifications:
  email:
    on_success: never
